name: Build Dobby Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build

      - name: Build Dobby
        env:
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          echo $ANDROID_NDK_ROOT
          python3 scripts/platform_builder.py --platform=android --arch=all

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dobby-android
          path: build/
